three column layout - Yuliia P.
yuliia-p/c0622-code-solutions pull request #18
Opened 2022-07-01 19:24 UTC by yuliia-p

<img width="1150" alt="Screen Shot 2022-06-30 at 11 35 55 PM" src="https://user-images.githubusercontent.com/106217355/176957508-84114e6a-7f3f-4bea-ad12-d1014ca8c7f3.png">

2022-07-01 22:05 UTC, codingcodymiller requested changes

2022-07-01 22:05 UTC, codingcodymiller commented on css-three-column-layout/styles.css
> +  margin: 30px;
Don't pollute your layout classes. The only styling on `column` classes should be `flex-basis`. If you need this, you should apply it to another class you can add in addition to the column class.

2022-07-01 22:05 UTC, codingcodymiller commented on css-three-column-layout/styles.css
> +  /* max-width: 800px; */
You should have a max width on your `container` class

2022-07-01 22:05 UTC, codingcodymiller commented on css-three-column-layout/styles.css
> +  /* justify-content: center; */
Please remove commented code prior to submitting for review.

2022-07-01 22:05 UTC, codingcodymiller commented on css-three-column-layout/styles.css
> +  margin-top: 24px; */
Please remove commented code prior to submitting for review.

2022-07-02 23:58 UTC, yuliia-p commented
<img width="1131" alt="Screen Shot 2022-07-02 at 4 50 00 PM" src="https://user-images.githubusercontent.com/106217355/177019389-f0eb7e78-a5d9-41da-b042-d316dd0cd45a.png">

2022-07-05 17:11 UTC, codingcodymiller requested changes

2022-07-05 17:11 UTC, codingcodymiller commented on css-three-column-layout/styles.css
> +  flex-basis: calc(100% / 3);
Why isn't this on a rule for `column-third`?

2022-07-06 16:24 UTC, codingcodymiller requested changes
My prior feedback was not addressed.

2022-07-07 05:08 UTC, yuliia-p commented
Fingers crossed
<img width="1093" alt="Screen Shot 2022-07-06 at 10 03 09 PM" src="https://user-images.githubusercontent.com/106217355/177695924-f28e1afe-e329-4ca2-a464-8102b291da7f.png">
d

2022-07-07 17:04 UTC, codingcodymiller requested changes
Hey Yuliia! Your headline is misaligned with the content below it, please revise and submit a new screenshot with your revision

2022-07-07 21:23 UTC, yuliia-p commented
<img width="929" alt="Screen Shot 2022-07-07 at 2 22 46 PM" src="https://user-images.githubusercontent.com/106217355/177873745-846a624f-d45f-4449-b62a-62d1e96ea4b1.png">

2022-07-07 23:18 UTC, merged