layout classes - Yuliia P.
yuliia-p/c0622-code-solutions pull request #19
Opened 2022-07-02 04:03 UTC by yuliia-p

<img width="988" alt="Screen Shot 2022-07-01 at 9 00 46 PM" src="https://user-images.githubusercontent.com/106217355/176985810-468368d2-a3a1-48fa-9c10-a1da8b65d3a7.png">

2022-07-05 17:08 UTC, codingcodymiller requested changes

2022-07-05 17:08 UTC, codingcodymiller commented on css-layout-classes/styles.css
> +}
Where are your rulesets for your `column` classes?

2022-07-06 00:52 UTC, yuliia-p commented
<img width="688" alt="Screen Shot 2022-07-05 at 5 51 37 PM" src="https://user-images.githubusercontent.com/106217355/177440047-fd7dccff-ab3e-4d21-92dd-2e6df6b3d736.png">

2022-07-06 16:22 UTC, codingcodymiller requested changes
You are still missing rules for `column-third`, `column-one-third` (which seems like it would be identical to `column-third` 🤔), and `column-full`.

2022-07-06 16:22 UTC, codingcodymiller commented on css-layout-classes/styles.css
> +.column-size {
Why isn't this the `column-fourth` rule? This is the class setting the size of the element 🤔

2022-07-06 21:09 UTC, yuliia-p commented
<img width="698" alt="Screen Shot 2022-07-06 at 2 08 06 PM" src="https://user-images.githubusercontent.com/106217355/177643563-13a255f1-9fb0-42ba-8009-7022f92d35d7.png">

2022-07-07 21:13 UTC, merged