two column layout - Yuliia P.
yuliia-p/c0622-code-solutions pull request #20
Opened 2022-07-03 01:35 UTC by yuliia-p

<img width="980" alt="Screen Shot 2022-07-02 at 6 33 58 PM" src="https://user-images.githubusercontent.com/106217355/177021044-2205f791-59d1-42e0-a180-d31567aeb043.png">

2022-07-05 17:18 UTC, codingcodymiller requested changes
Hey Yuliia, the spacing of the content in your output does not match the example, please revise and submit a new screenshot with your revision.

2022-07-06 06:26 UTC, yuliia-p commented
<img width="1004" alt="Screen Shot 2022-07-05 at 11 22 17 PM" src="https://user-images.githubusercontent.com/106217355/177483210-e973b53d-17d7-4436-a0a1-3d607f3f31ee.png">

2022-07-06 16:27 UTC, codingcodymiller requested changes

2022-07-06 16:27 UTC, codingcodymiller commented on css-two-column-layout/index.html
> +    <div class="row-header">
`row-header`? Why not just `row`? You should make a `column` element inside this `row` to control the size of the content, too

2022-07-06 16:27 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +  flex-basis: 50%;
Why isn't this on a rule for the `half-column` class?

2022-07-07 17:05 UTC, codingcodymiller requested changes
In addition to my other comments, you are still missing a rule for `column-three-quarters`

2022-07-11 17:26 UTC, codingcodymiller approved these changes

2022-07-12 03:42 UTC, merged