css-canvas-medical - Yuliia P.
yuliia-p/c0622-code-solutions pull request #21
Opened 2022-07-04 16:47 UTC by yuliia-p

<img width="578" alt="Screen Shot 2022-07-04 at 9 46 11 AM" src="https://user-images.githubusercontent.com/106217355/177194345-dcc5fbb6-8bbc-48ed-8491-d25b3ae4724b.png">

2022-07-08 06:08 UTC, yuliia-p commented
<img width="638" alt="Screen Shot 2022-07-07 at 11 08 28 PM" src="https://user-images.githubusercontent.com/106217355/177927758-fc8c7c6e-b7b1-4905-b419-518eb6f348e4.png">

2022-07-08 22:40 UTC, codingcodymiller requested changes

2022-07-08 22:40 UTC, codingcodymiller commented on css-canvas-medical/styles.css
> +.column-two-fourths {
`column-half`?

2022-07-08 22:40 UTC, codingcodymiller commented on css-canvas-medical/styles.css
> +  margin-left: 50px;
Don't pollute your layout classes, make these into a separate rule

2022-07-11 17:28 UTC, codingcodymiller commented on css-canvas-medical/styles.css
> +.column-two-fourths {
This still needs to be addressed.

2022-07-11 17:29 UTC, codingcodymiller requested changes

2022-07-11 17:29 UTC, codingcodymiller commented on css-canvas-medical/styles.css
> +.column-two-fourths {
This still needs to be addressed.

2022-08-09 18:40 UTC, yuliia-p commented
<img width="332" alt="Screen Shot 2022-08-09 at 11 37 34 AM" src="https://user-images.githubusercontent.com/106217355/183735854-08dbc3bf-16d6-494d-b73a-c3cc40003f6f.png">
<img width="323" alt="Screen Shot 2022-08-09 at 11 37 42 AM" src="https://user-images.githubusercontent.com/106217355/183735871-284e8fd4-d73e-4dbe-882e-46ea2cb2de8a.png">

2022-08-16 00:37 UTC, thebearingedge approved these changes

2022-08-16 03:09 UTC, merged