javascript-if - Yuliia P.
yuliia-p/c0622-code-solutions pull request #32
Opened 2022-07-07 23:04 UTC by yuliia-p

<img width="503" alt="Screen Shot 2022-07-07 at 3 59 03 PM" src="https://user-images.githubusercontent.com/106217355/177885662-f63e13cb-6fc4-40af-b1e4-fb14c3cd608c.png">
<img width="513" alt="Screen Shot 2022-07-07 at 4 00 14 PM" src="https://user-images.githubusercontent.com/106217355/177885673-520adda8-6524-48b9-a095-e7be052d06f9.png">
<img width="491" alt="Screen Shot 2022-07-07 at 4 03 04 PM" src="https://user-images.githubusercontent.com/106217355/177885681-6779683e-cc54-4634-adff-e2f8ebaab725.png">

2022-07-07 23:39 UTC, yuliia-p commented
<img width="461" alt="Screen Shot 2022-07-07 at 4 38 51 PM" src="https://user-images.githubusercontent.com/106217355/177888819-ea188cce-30b2-4705-89a5-cfb15a3b5b6d.png">

2022-07-08 00:09 UTC, yuliia-p commented
<img width="445" alt="Screen Shot 2022-07-07 at 5 09 13 PM" src="https://user-images.githubusercontent.com/106217355/177891305-345d732e-41c5-404f-ad61-93949118b285.png">

2022-07-08 22:00 UTC, codingcodymiller requested changes

2022-07-08 22:00 UTC, codingcodymiller commented on javascript-if/main.js
> +var msg = ' ';
You should have this `msg` variable inside the `categorizeAcidity` function

2022-07-08 22:00 UTC, codingcodymiller commented on javascript-if/main.js
> +var catchPhrase = ' ';
Same here, this should be within the function definition

2022-07-08 22:38 UTC, codingcodymiller approved these changes

2022-07-08 22:39 UTC, merged