String manipulation 1 - Yuliia P.
yuliia-p/c0622-code-solutions pull request #37
Opened 2022-07-10 05:24 UTC by yuliia-p

2022-07-11 18:01 UTC, codingcodymiller requested changes
Hey Yuliia, please resubmit this with pseudocode for each of your solutions.

Additionally, please always provide a screenshot showing all of your tests passing.

2022-07-12 02:08 UTC, yuliia-p commented
<img width="510" alt="Screen Shot 2022-07-11 at 2 31 36 PM" src="https://user-images.githubusercontent.com/106217355/178392961-02645577-61e5-4586-be2b-316de71513c4.png">
<img width="524" alt="Screen Shot 2022-07-11 at 2 34 35 PM" src="https://user-images.githubusercontent.com/106217355/178392965-b51b2f43-0a9f-48fd-82f7-18b40496cd9b.png">
<img width="424" alt="Screen Shot 2022-07-11 at 7 05 46 PM" src="https://user-images.githubusercontent.com/106217355/178392969-8404b0d5-62c1-45a0-93dc-305997e97a5e.png">

2022-07-12 02:11 UTC, yuliia-p commented
![Uploading Screen Shot 2022-07-11 at 7.10.30 PM.png…]()

2022-07-12 19:53 UTC, codingcodymiller approved these changes

2022-07-13 05:35 UTC, merged