Javascript forms - Yuliia P.
yuliia-p/c0622-code-solutions pull request #45
Opened 2022-07-13 21:31 UTC by yuliia-p

https://user-images.githubusercontent.com/106217355/178840060-39b709d6-a7c1-451a-8671-8e666caa3d0e.mp4

2022-07-13 22:39 UTC, codingcodymiller requested changes

2022-07-13 22:39 UTC, codingcodymiller commented on javascript-forms/form-events.js
> +elTextInput.addEventListener('input', handleInput);
You should be adding all three event listeners to all three form control elements

2022-07-15 22:13 UTC, yuliia-p commented
<img width="676" alt="Screen Shot 2022-07-15 at 3 12 39 PM" src="https://user-images.githubusercontent.com/106217355/179317894-3a98d555-d198-4ac4-b8df-4dc33b0c5c40.png">

2022-07-18 16:12 UTC, codingcodymiller approved these changes

2022-07-18 17:58 UTC, merged