css-media-queries - Yuliia P.
yuliia-p/c0622-code-solutions pull request #48
Opened 2022-07-14 05:11 UTC by yuliia-p

https://user-images.githubusercontent.com/106217355/178904134-09186e21-156f-437d-b454-f03e03771c53.mp4

2022-07-14 05:12 UTC, yuliia-p commented
https://user-images.githubusercontent.com/106217355/178904174-1aa4ca7a-91fb-45ce-8731-f5ebbf09df8b.mp4

2022-07-14 05:12 UTC, yuliia-p commented
https://user-images.githubusercontent.com/106217355/178904219-687a0ddb-b3c1-4ddc-a377-07a0d6c6bb04.mov

2022-07-14 18:32 UTC, codingcodymiller requested changes

2022-07-14 18:32 UTC, codingcodymiller commented on css-media-queries/at-media.html
> +}
Careful with indentation 😬

2022-07-14 18:32 UTC, codingcodymiller commented on css-media-queries/breakpoints.html
> +    }
Careful with indentation 😬

2022-07-14 18:32 UTC, codingcodymiller commented on css-media-queries/meta-viewport.html
> +    }
Careful with indentation 😬

2022-07-14 23:40 UTC, codingcodymiller requested changes

2022-07-14 23:40 UTC, codingcodymiller commented on css-media-queries/at-media.html
> +      }
This is still incorrect indentation

2022-07-14 23:40 UTC, codingcodymiller commented on css-media-queries/breakpoints.html
> +      }
This is still incorrect indentation

2022-07-15 23:35 UTC, yuliia-p commented
<img width="587" alt="Screen Shot 2022-07-15 at 4 34 53 PM" src="https://user-images.githubusercontent.com/106217355/179324477-278e3cb8-5427-483b-8f23-1dff2911e2e3.png">
<img width="442" alt="Screen Shot 2022-07-15 at 4 35 05 PM" src="https://user-images.githubusercontent.com/106217355/179324480-b166f32a-d042-420a-9cb6-e6c2bf794c93.png">
<img width="469" alt="Screen Shot 2022-07-15 at 4 35 11 PM" src="https://user-images.githubusercontent.com/106217355/179324482-8c952576-b9e8-47a2-9da7-784fbda182ab.png">

2022-07-18 16:12 UTC, codingcodymiller requested changes
This is still incorrect, properties are supposed to be indented by one tab from the selector

2022-07-19 04:21 UTC, yuliia-p commented
<img width="527" alt="Screen Shot 2022-07-18 at 9 20 28 PM" src="https://user-images.githubusercontent.com/106217355/179664019-712d55eb-ed9a-4d11-ab99-17cef1f0fb05.png">

2022-07-20 22:02 UTC, codingcodymiller approved these changes

2022-07-20 22:54 UTC, merged