String manipulation 2 - Yuliia P.
yuliia-p/c0622-code-solutions pull request #56
Opened 2022-07-18 01:50 UTC by yuliia-p

<img width="649" alt="Screen Shot 2022-07-17 at 6 45 31 PM" src="https://user-images.githubusercontent.com/106217355/179434719-df8a0636-f599-405c-a982-04cd72a39df3.png">
<img width="634" alt="Screen Shot 2022-07-17 at 6 46 26 PM" src="https://user-images.githubusercontent.com/106217355/179434724-d5436b8e-4035-43b3-900b-bc27b781e348.png">
<img width="647" alt="Screen Shot 2022-07-17 at 6 47 57 PM" src="https://user-images.githubusercontent.com/106217355/179434732-604ba5f2-2283-49a5-a8e3-2699addcd3b7.png">
<img width="651" alt="Screen Shot 2022-07-17 at 6 49 04 PM" src="https://user-images.githubusercontent.com/106217355/179434737-12acee60-758c-4077-880f-60ac83d3358f.png">

2022-07-18 16:30 UTC, codingcodymiller requested changes

2022-07-18 16:30 UTC, codingcodymiller commented on string-manipulation-2/src/capitalize-word.js
> +    return word.charAt(0).toUpperCase() + word.slice(1, 4).toLowerCase() + word.charAt(4).toUpperCase() + word.slice(5).toLowerCase();
In special cases like this, you don't need to manually put this together. You can just `return "javaScript";`

2022-07-18 16:30 UTC, codingcodymiller commented on string-manipulation-2/src/num-vowels.js
> +    var vowels = string.match(/[aeiou]/gi);
You should do this without RegEx

2022-07-19 05:16 UTC, yuliia-p commented
<img width="644" alt="Screen Shot 2022-07-18 at 10 15 31 PM" src="https://user-images.githubusercontent.com/106217355/179670539-f59c4b8e-5bc2-44e7-857c-1a9532b77771.png">
<img width="764" alt="Screen Shot 2022-07-18 at 10 14 22 PM" src="https://user-images.githubusercontent.com/106217355/179670551-446a381e-c968-45d2-9ce9-8806bafea3b0.png">

2022-07-25 22:13 UTC, codingcodymiller requested changes

2022-07-25 22:13 UTC, codingcodymiller commented on string-manipulation-2/src/capitalize-word.js
> +    return word.charAt(0).toUpperCase() + word.slice(1, 4).toLowerCase() + word.charAt(4).toUpperCase() + word.slice(5).toLowerCase();
In special cases like this, you don't need to do the work of assembling the value if you already know what you need to return. You can just `return "JavaScript"` 🤓

2022-07-25 22:13 UTC, codingcodymiller commented on string-manipulation-2/src/capitalize-words.js
> +    var Str = newArr.join(' ');
You should do this after the loop has ended.

2022-07-25 22:13 UTC, codingcodymiller commented on string-manipulation-2/src/num-vowels.js
> +    var vowels = string.match(/[aeiou]/gi);
This still needs to be addressed

2022-07-25 23:29 UTC, codingcodymiller approved these changes

2022-07-25 23:32 UTC, merged