html-relative-links - Yuliia P.
yuliia-p/c0622-code-solutions pull request #6
Opened 2022-06-28 17:47 UTC by yuliia-p

https://user-images.githubusercontent.com/106217355/176248836-78d91385-1829-466a-9731-fdd7fb4f12fc.mp4

2022-06-28 17:50 UTC, codingcodymiller requested changes
Make sure to double-check that you have completed everything requested before submitting for review 👀

2022-06-28 17:50 UTC, codingcodymiller commented on html-relative-links/about-me.html
> +  <img src="https://pbs.twimg.com/media/EwxVoP5W8Ac4cVV.jpg" alt="Girl holding programming book">
You should be using the images in the `images` directory

2022-06-28 17:50 UTC, codingcodymiller commented on html-relative-links/about-me.html
> +    <li>About Me</li>
Missed this one.

2022-06-28 17:50 UTC, codingcodymiller commented on html-relative-links/about-me/about-me.html
> +  <img src="???" alt="Girl holding programming book">
None of this is complete.

2022-06-28 17:50 UTC, codingcodymiller commented on html-relative-links/contact-us/contact-us.html
> +  <img src="???" alt="Girl holding programming book">
None of this is complete.

2022-06-28 17:50 UTC, codingcodymiller commented on html-relative-links/contact-us.html
> +    <li>Contact Us</li>
Missed this one.

2022-06-28 17:50 UTC, codingcodymiller commented on html-relative-links/contact-us.html
> +    src="https://images.squarespace-cdn.com/content/v1/60b7f1bed70b3159a0b9141d/1645987750387-5MXLHRAKAIAM78AUZKYI/photo6109534113649242172.jpg"
Again, use the images in the `images` directory

2022-06-28 19:10 UTC, yuliia-p commented
https://user-images.githubusercontent.com/106217355/176264794-207e8ad3-48c5-43d7-b144-54132b4f2e94.mp4

2022-06-29 03:19 UTC, yuliia-p commented
https://user-images.githubusercontent.com/106217355/176343869-a45914e6-8ffc-4c85-9062-2a0509a90105.mp4

2022-06-29 16:08 UTC, codingcodymiller approved these changes

2022-06-29 18:06 UTC, merged