completed express-get-json - Yuliia P.
yuliia-p/c0622-code-solutions pull request #87
Opened 2022-08-19 20:25 UTC by yuliia-p

<img width="1025" alt="Screen Shot 2022-08-19 at 1 22 25 PM" src="https://user-images.githubusercontent.com/106217355/185701513-6ddaa2ad-c341-4e60-ba18-19d00162f3d9.png">

2022-08-19 20:28 UTC, yuliia-p commented
<img width="347" alt="Screen Shot 2022-08-19 at 1 27 55 PM" src="https://user-images.githubusercontent.com/106217355/185701987-2ce54f27-91f6-4c16-826c-339c950d3f0c.png">

2022-08-19 23:02 UTC, thebearingedge requested changes

2022-08-19 23:02 UTC, thebearingedge commented on express-get-json/index.js
> +    newGradesArr.push(key, grades[key]);
This is pushing string keys and objects into the array try removing the `key` argument.

```js
newGradesArr.push(grades[key]);
```

2022-08-20 16:12 UTC, yuliia-p commented
<img width="1234" alt="Screen Shot 2022-08-20 at 9 11 09 AM" src="https://user-images.githubusercontent.com/106217355/185756235-7f365a0d-4254-4667-8691-f469c331ca89.png">
<img width="413" alt="Screen Shot 2022-08-20 at 9 11 22 AM" src="https://user-images.githubusercontent.com/106217355/185756245-ffc8d841-429d-4932-bd38-be69530fc1c7.png">

2022-08-20 16:33 UTC, thebearingedge approved these changes

2022-08-23 00:31 UTC, merged